# Generated by Django 5.0 on 2024-01-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='nombre',
        ),
    ]
